POST https://sfgc-website-api.onrender.com/posts
Content-type: application/json

    {
        "title": "titulo de teste",
        "description": " teste de descrição",
        "dateEvent": "20/06/2024"
    }

###
GET https://sfgc-website-api.onrender.com/posts

###
PUT https://sfgc-website-api.onrender.com/posts/3
Content-type: application/json

    {
        "title": "titulo de teste editado",
        "description": " teste de descrição editado",
        "dateEvent": "25/06/2024"
    }

###
DELETE https://sfgc-website-api.onrender.com/posts/3